export const initialUsers = [
  {
    key: 1,
    name: "Somchai Prasert",
    email: "somchai.prasert@acme.com",
    groups: ["Security"],
    zones: ["Low Zone", "Normal Zone"],
    status: "Active",
    avatar: "SP",
    company: "ACME Facility",
    position: "Security Supervisor",
    joined: "2024-07-23",
    locked: true,
  },
  {
    key: 2,
    name: "Somsri Kittisak",
    email: "somsri.kittisak@acme.com",
    groups: ["Engineering"],
    zones: ["High Zone"],
    status: "Active",
    avatar: "SK",
    company: "ACME Facility",
    position: "Engineer",
    joined: "2024-07-20",
  },
  {
    key: 3,
    name: "John Doe",
    email: "john.doe@betacorp.com",
    groups: ["Control Room"],
    zones: ["High Zone"],
    status: "Inactive",
    avatar: "JD",
    company: "BetaCorp",
    position: "Control Room Operator",
    joined: "2024-07-21",
    locked: true,
  },
  {
    key: 4,
    name: "Jane Smith",
    email: "jane.smith@betacorp.com",
    groups: ["Visitor"],
    zones: ["Normal Zone"],
    status: "Pending",
    avatar: "JS",
    company: "BetaCorp",
    position: "Consultant",
    joined: "2024-07-23",
  },
  {
    key: 5,
    name: "Anan Chaiyaporn",
    email: "anan.chaiyaporn@acme.com",
    groups: ["Engineering"],
    zones: ["Low Zone"],
    status: "Active",
    avatar: "AC",
    company: "ACME Facility",
    position: "Technician",
    joined: "2024-07-22",
  },
  {
    key: 6,
    name: "Wanwisa Suksawat",
    email: "wanwisa.suksawat@acme.com",
    groups: ["Security"],
    zones: ["Low Zone"],
    status: "Active",
    avatar: "WS",
    company: "ACME Facility",
    position: "Security Officer",
    joined: "2024-07-23",
  },
];
